version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5485:5432

  redis:
    image: redis
    ports:
      - 6385:6379

  web:
    build: .
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file: conf/dockers.env
    depends_on:
      - db
      - redis